name: Execute Tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
      - name: Generate JaCoCo Badge
          uses: cicirello/jacoco-badge-generator@v2
          with:
            jacoco-csv-file: target/site/jacoco/jacoco.csv
            badges-directory: .github/badges
            generate-coverage-badge: true
            coverage-badge-filename: jacoco.svg
            generate-branches-badge: true
            branches-badge-filename: branches.svg
            coverage-endpoint-filename: jacoco.json
            branches-endpoint-filename: branches.json
            generate-summary: true
            summary-filename: coverage-summary.json
            coverage-label: coverage
            branches-label: branches
            colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
            intervals: 100 90 80 70 60 0
            on-missing-report: fail
            fail-if-coverage-less-than: 10
            fail-if-branches-less-than: 10